version: '3.4'

services:
  ard-connector:
    image: lunatrik/ard-connector:latest
    build:
      context: .
      dockerfile: Lunatrik.ARDConnector/Dockerfile

    env_file:
      - .env

    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Discord_Webhook=${DISCORD_WEBHOOK}
      - BasicAuth:Username=${BASICAUTH_USERNAME}
      - BasicAuth:Password=${BASICAUTH_PASSWORD}

    command: dotnet Lunatrik.ARDConnector.dll

     


