version: '3.8'

services:
  ard-connector:
    image: lunatrik/ard-connector:latest

    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Discord_Webhook=${DISCORD_WEBHOOK}
      - BasicAuth:Username=${BASICAUTH_USERNAME}
      - BasicAuth:Password=${BASICAUTH_PASSWORD}

    command: dotnet Lunatrik.ARDConnector.dll
    networks:
      - traefik-public
 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.ard-http.rule=Host(`${HOST_API?Variable not set}`)
        - traefik.http.routers.ard-http.entrypoints=http
        - traefik.http.routers.ard-http.middlewares=websecure
        - traefik.http.routers.ard-https.rule=Host(`${HOST_API?Variable not set}`)
        - traefik.http.routers.ard-https.entrypoints=https
        - traefik.http.routers.ard-https.tls=true
        - traefik.http.routers.ard-https.tls.certresolver=le
        - traefik.http.services.ard.loadbalancer.server.port=80
networks:
  traefik-public:
    external: true
      