version: '3.4'



services:
  ard-connector:
    image: lunatrik/ard-connector:latest
    env_file:
      - .env

    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Discord_Webhook=${DISCORD_WEBHOOK}
      - BasicAuth:Username=${BASICAUTH_USERNAME}
      - BasicAuth:Password=${BASICAUTH_PASSWORD}

    command: dotnet Lunatrik.ARDConnector.dll
    networks:
      - net
      - traefik-public
 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.ard-connector.rule=Host(${HOST})
        - traefik.http.routers.ard-connector.entrypoints=https
        - traefik.http.routers.ard-connector.tls=true
        - traefik.http.routers.ard-connector.tls.certresolver=le
        - traefik.http.services.ard-connector.loadbalancer.server.port=80
        - traefik.http.services.ard-connector.loadbalancer.passhostheader=true
        - traefik.http.routers.ard-connector.middlewares=forwardedheaders

        - traefik.http.routers.ard-connector-http.rule=Host(${HOST})
        - traefik.http.routers.ard-connector-http.entrypoints=http
        - traefik.http.routers.ard-connector-http.middlewares=forwardedheaders

networks:
  traefik-public:
    external: true
  net:
    external: true
     


